### PR TITLE
Structured the home page to improve readability.

### PR DESCRIPTION
**Pull request by papercheck**
Structured the home page to make critical node details easier to read. Simple html update using w3css.

### CODE REVIEW

**Comment by cryptosharks131** [comment]
Wow, this first pass looks really cool. Love to see more of this styling!

image

**Comment by thibautrey** [comment]
@papercheck this looks very good. Mind if I give it a shot as well and improve on your design?
I'm thinking tabs instead of having to scroll all the way down. Also making it more smartphone friendly. I like to watch mine on my phone. I'll checkout from your branch if that's okay.

**Comment by papercheck** [comment]
@thibautrey, go for it! I did this when I had some extra bandwidth, then @cryptosharks131 updated to 1.0.2. I was trying to use the libraries he used and didn't want to take too much liberty with changing the layout. In any case, go for it! I would like to jump back-in, but haven't had a chance.

**Comment by thibautrey** [comment]
After some review of the codebase I realise it isn't future proof in term of UI. I think we are better off ditching the existing UI and rebasing on something more modern like react. I'll try to bootstrap something and convert the current interfaces.

This will simplify onboarding new frontend developers and therefore accelerate the iterations on the project

**Comment by cryptosharks131** [comment]
This was the plan in the beginning @thibautrey and I did start a react integration branch.  I just rebased it with master so it should have the most recent updates. I didn't get farther than just setting up a basic channels page with it though as its still a bit of a learning curve for me.

https://github.com/cryptosharks131/lndg/tree/react-frontend

Most all the LNDg data is already available over API so moving to react should be pretty easy overall.

**Comment by papercheck** [comment]
I think you guys are on the right track @cryptosharks131 and @thibautrey.

**Comment by SuperAtic** [comment]
@cryptosharks131 great move thinking on react terms 💪 I'll have a bit of a learning curve too but happy to contribute from a Ui/Ux perspective if needed

**Comment by papercheck** [comment]
@SuperAtic, wow, that looks amazing! I hope that is included in a future version release.

**Comment by SuperAtic** [comment]
@papercheck hope too :)

**Comment by Wired4ncer** [comment]
This looks really sleek. Looking forward to see it released in the future!

**Comment by SuperAtic** [comment]
FYI: working on a newer version now :) https://makers.bolt.fun/project/LNDg

**Pull request closed without merging**
