### PR TITLE
Fix directory creation and variable expansion in scripts

### PR DESCRIPTION
**Pull request by federicociro**
## Fixes

This pull request addresses several issues found in the deployment scripts where directories may not exist before attempting file operations, and a variable expansion issue within a heredoc block.

### Changes
- A check is added to ensure the `$HOME_DIR/lndg` directory exists before any file operations are performed within it.
- Corrected the heredoc syntax in `nginx.sh` to allow variable expansion, ensuring the correct path is used.
- Added creation and permission setting for the `/var/log/uwsgi` directory to prevent permission errors.
- Implemented a check for the existence of the directory for the `.sock` file to avoid errors when touching the `lndg.sock` file.

### Testing
- The changes have been locally tested to ensure each script section now executes without errors regarding missing directories or file paths.
- Full deployment process was run to ensure no other issues arise with these changes.

### CODE REVIEW

**Comment by federicociro** [comment]
Hello @cryptosharks131!

I made some changes as script was not running in an LxC container running with root. I went a bit wild and took the liberty of improving it a bit too.

Looking forward to hearing your feedback about it.


Best regards,
Federico.

**Comment by cryptosharks131** [comment]
Hi @federicociro and thanks for the PR!

I have updated the target branch to `v1.8.0` so that we can resolve any issues with the updates already merged for `nginx.sh`.

Previous commit:
https://github.com/cryptosharks131/lndg/commit/ba7d1c5ffd76ca26222fbfc9189c0e3dbf058b8c#diff-e8f0485714e2f10b2f9f1470b94c92684176a8b62c3e1620496fd38105c7bdf7

**Comment by cryptosharks131** [comment]
Hi @federicociro, would you like to review this for the `v1.8.0` update and resolve the conflicts?

**Comment by federicociro** [comment]
Hi @cryptosharks131,
I've resolved the conflicts in the script as part of this pull request. The updates include harmonizing the use of the LNDG_DIR variable across the script for improved flexibility and consistency. This change aligns with the modifications introduced in the v1.8.0 branch.

Key updates include:
1. Standardizing the directory paths to use $LNDG_DIR.
2. Updating the uWSGI configuration (lndg.ini) to reflect the consolidated directory structure and adding logging configurations.
3. Refining the uWSGI parameters (uwsgi_params) file for better readability and maintaining variable consistency.
4. Modifying the systemd unit file for uWSGI to incorporate the new path and additional settings for enhanced control.
5. Adjusting the Nginx configuration to match the updated path and socket references.

These updates ensure that the script is more maintainable and aligns with the best practices as seen in the v1.8.0 branch. I've thoroughly tested the changes in a controlled environment, and everything appears to function as expected. However, I would appreciate any additional reviews or testing you might deem necessary.

Looking forward to your feedback and any further suggestions you might have.

Best regards,
Federico.

**Pull request merged**
