### PR TITLE
Temporary, but working, fix for the balance horizontal histogram and the active channels section being too large and not scrollable

### PR DESCRIPTION
**Pull request by asvdf**
Please accept this small contribution 🗡️

### CODE REVIEW

**Comment by cryptosharks131** [comment]
The scroll bar is a great idea, I think it just needed to be moved under the active channels specifically and only in the horizonal direction.  I added this to master for now: https://github.com/cryptosharks131/lndg/commit/2da4580c5addebf107bd4553a9d9ad0f288126a4

Attempted the new balance bar but it did not look so good so maybe this can be reworked a little better. Imagine a better visual can done than the current implementation.

A new order might also be beneficial, though we would want a similar flow of columns for the inactive and pending channels as well. Have considered removing peer pubkey as well to reclaim horizontal space on the page but it is valuable to have at times as well.

**Comment by asvdf** [comment]
The bar is definitely raw, yes, I suppose it's a personal taste at that since yours looks way better, even if at low local ratio, at least for me (both in firefox and chrome anyway) it doesn't scale, and still shows more than the real local.
Also there's the problem where it needs a zoomed out view or you only see a small blue rectangle.

I ended up hacking together an ugly code that shows me ascii balance bars in telegram :D

**Comment by asvdf** [comment]
Re: the bar only under the active channels section, I think that would require a container div around the table.
Better yet, ditch the whole table and only use div layout.
Even better, place pubkey in a hover dialogue, or copy-on-click action button like thunderhub, or split each channel row in two rows.
That would require too much of my resources though, with everything I still need to tweak on my node's scripts, I've not worked on web UI for quite a while and I'm rusty

**Comment by cryptosharks131** [comment]
Made a few updates based on your suggestion to clean up the active channels a bit. https://github.com/cryptosharks131/lndg/commit/de57bfee25a4ab11064fdd510eddd608ca03c1dc

Will close this PR for now, thanks for your suggestions!

**Pull request closed without merging**
